### ISSUE TITLE
Multi platform library?

### ISSUE THREAD

**Issue by ExoSkye** [Electron-x/GbxDump#1]
Hey, I'm writing a re-implementation of TrackMania Nations Forever ([https://github.com/ProtoByter/ReMania-NF](https://github.com/ProtoByter/ReMania-NF)) and I'm trying to make it crossplatform. 
I've found this great utility but it makes heavy use of the Win32 API, which makes it very annoying (or impossible) to convert it to cross platform code. I'd like to not have to re-implement the 4500+ lines of code that you have written. Would it be possible to convert this into a cross platform library? Or would it be possible to provide a specification of the gbx file format? because I haven't been able to find one online

**Comment by dracc** [comment]
Read the readme, a GBX specification can be found in the links towards the end.

**Comment by ExoSkye** [comment]
oh hi @dracc

**Comment by ExoSkye** [comment]
frick must've not seen it
